export const JWT_PUBLIC_KEY = process.env.JWT_PUBLIC_KEY || `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkbO7uzJZMVB3AzuNUoTc
ZKFJMMRg1ICG++lKn4QxbJXAs6lfdfxt1JPFtjKwmUGW9A1YFem5SxOwiyPZXEwN
IHsEj5tBnFxG0fkuApbl8x6vkXwHneQNC1Edz3nTALMAG7ydS5Td5VS/CKQciQVt
lfqyh7x8s2p+har5asQT4dz65s0Ge8BcS2HPDR3l4rpFU4RlexjmXfK0TtWpEAeJ
Ee2YDcJnMPKnzByH+0CLGwlmpDLcAdgXq0o5p8eTgoc0kVJAVbUFra1sztqs9HKf
wxvBtl4hWGAsV0L4sAkayzjNIq+nSV02OdQeC6pvsME3aVWJJlYQIEUAJkdpn/OM
8QIDAQAB
-----END PUBLIC KEY-----
`;